blank_issues_enabled: false
contact_links:
  - name: â“ Questions, Help, and Advice
    url: https://github.com/material-components/material-web/discussions
    about: For general support, please refer to the Material Web discussion board.

  - name: ğŸ’¬ Chat
    url: https://lit.dev/discord/
    about: Alternatively, you can join the Lit Discord and join the `#material` channel to talk to the team.
