name: Update API Docs

on:
  push:
    branches: main
  workflow_dispatch:
    # allows triggering from the github UI
jobs:
  check-for-doc-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install Dependencies
        run: npm ci

      - name: Update Docs
        run: npm run update-docs

      - name: Check if update-docs produces git diff
        id: ifChange
        run: git diff --exit-code || echo "::set-output name=changed::yes"

      - name: Create PR
        if: steps.ifChange.outputs.changed == 'yes'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.LIT_ROBOT_ACCESS_TOKEN }}
          commit-message: 'docs: update API docs'
          author: lit-robot <lit-robot@google.com>
          committer: lit-robot <lit-robot@google.com>
          title: 'docs: update API docs'
          body: This PR was auto generated by the update-docs-on-main GitHub action.
          reviewers: e111077,asyncliz,AndrewJakubowicz
          branch: auto-update-docs
          labels: |
            Ready for Google
            preview-catalog
