name: Update size

on:
  push:
    branches: main
  workflow_dispatch:
    # allows triggering from the github UI
jobs:
  check-for-doc-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install Dependencies
        run: npm ci

      - name: Update Size
        run: npm run update-size

      - name: Check if update-size produces git diff
        id: ifChange
        run: git diff --exit-code || echo "::set-output name=changed::yes"

      - name: Create or update PR
        if: steps.ifChange.outputs.changed == 'yes'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.LIT_ROBOT_ACCESS_TOKEN }}
          commit-message: 'chore: update sizes'
          author: lit-robot <lit-robot@google.com>
          committer: lit-robot <lit-robot@google.com>
          title: 'chore: update sizes'
          body: This PR was auto generated by the update-size-on-main GitHub action.
          branch: auto-update-sizes
          # Don't automatically add reviewers or Ready for Google label until we're ready
          # since this will be noisy.
